/* Rasterises site/favicon.svg into the formats that cannot take an SVG.
 *
 *   node tools/build-favicon.mjs
 *
 * Writes site/favicon.ico (a 32x32 PNG in an ICO wrapper, for browsers that
 * request /favicon.ico) and site/apple-touch-icon.png (180x180, for iOS home
 * screens). No npm dependencies — the shapes are circles, so they are drawn
 * directly and encoded with Node's own zlib.
 *
 * The geometry below mirrors favicon.svg. Change one, run this, and they match.
 */
import { writeFileSync } from 'node:fs';
import { deflateSync } from 'node:zlib';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'site');

const INK = [0x11, 0x11, 0x11];
const PAPER = [0xf9, 0xf7, 0xf1];

// In a 32-unit coordinate space. Sprinkles are deliberately off the clock
// positions — evenly spaced dots of this size read as bolt holes on a gear
// rather than sprinkles on a doughnut.
const RING_INNER = 4.9, RING_OUTER = 12.4, SPRINKLE_R = 1.3;
const SPRINKLES = [
  [16.2, 7.9], [22.6, 12.6], [22.2, 20.8],
  [15.2, 24.0], [9.3, 19.3], [9.6, 11.5],
];

/* Colour of one point in the 32-unit space, or null for the ink background. */
function paperAt(x, y) {
  const d = Math.hypot(x - 16, y - 16);
  if (d < RING_INNER || d > RING_OUTER) return false;          // hole, or outside
  for (const [sx, sy] of SPRINKLES) {
    if (Math.hypot(x - sx, y - sy) <= SPRINKLE_R) return false; // sprinkle
  }
  return true;
}

/* 4x4 supersampling, so the curves do not come out jagged at 32px. */
function render(size) {
  const px = Buffer.alloc(size * size * 4);
  const scale = 32 / size;
  const S = 4;
  for (let py = 0; py < size; py++) {
    for (let pxi = 0; pxi < size; pxi++) {
      let hits = 0;
      for (let sy = 0; sy < S; sy++) {
        for (let sx = 0; sx < S; sx++) {
          const x = (pxi + (sx + 0.5) / S) * scale;
          const y = (py + (sy + 0.5) / S) * scale;
          if (paperAt(x, y)) hits++;
        }
      }
      const t = hits / (S * S);
      const o = (py * size + pxi) * 4;
      for (let c = 0; c < 3; c++) px[o + c] = Math.round(INK[c] + (PAPER[c] - INK[c]) * t);
      px[o + 3] = 255;
    }
  }
  return px;
}

/* ---------- PNG encoder ---------- */
const CRC_TABLE = (() => {
  const t = new Int32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c;
  }
  return t;
})();
function crc32(buf) {
  let c = 0xffffffff;
  for (const b of buf) c = CRC_TABLE[(c ^ b) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}
function chunk(type, data) {
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length);
  const body = Buffer.concat([Buffer.from(type, 'ascii'), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body));
  return Buffer.concat([len, body, crc]);
}
function png(size, pixels) {
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(size, 0);
  ihdr.writeUInt32BE(size, 4);
  ihdr[8] = 8;    // bit depth
  ihdr[9] = 6;    // RGBA
  // Each scanline is prefixed with filter type 0.
  const raw = Buffer.alloc(size * (size * 4 + 1));
  for (let y = 0; y < size; y++) {
    raw[y * (size * 4 + 1)] = 0;
    pixels.copy(raw, y * (size * 4 + 1) + 1, y * size * 4, (y + 1) * size * 4);
  }
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', deflateSync(raw, { level: 9 })),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}

/* ---------- ICO wrapper ---------- */
// An .ico may hold a PNG directly, which every browser that still asks for
// favicon.ico understands.
function ico(size, pngBuf) {
  const header = Buffer.alloc(6);
  header.writeUInt16LE(0, 0);      // reserved
  header.writeUInt16LE(1, 2);      // type: icon
  header.writeUInt16LE(1, 4);      // one image
  const entry = Buffer.alloc(16);
  entry[0] = size >= 256 ? 0 : size;
  entry[1] = size >= 256 ? 0 : size;
  entry[2] = 0;                    // palette
  entry[3] = 0;                    // reserved
  entry.writeUInt16LE(1, 4);       // colour planes
  entry.writeUInt16LE(32, 6);      // bits per pixel
  entry.writeUInt32LE(pngBuf.length, 8);
  entry.writeUInt32LE(22, 12);     // offset: 6 header + 16 entry
  return Buffer.concat([header, entry, pngBuf]);
}

/* ---------- SVG ---------- */
// Emitted from the same constants, so the vector and the rasters cannot drift.
const ringMid = (RING_INNER + RING_OUTER) / 2;
const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" role="img" aria-label="Doughnut Days">
  <!-- Generated by tools/build-favicon.mjs. Edit the constants there, not here.
       This is the blog list's doughnut redrawn for a 16px tab: that one is a
       2px-stroke line drawing at 24px, and strokes that fine disappear at
       favicon size, so the ring is a solid band here. Ink tile so it holds up
       on light and dark tab strips. -->
  <rect width="32" height="32" fill="#111"/>
  <circle cx="16" cy="16" r="${ringMid}" fill="none" stroke="#f9f7f1" stroke-width="${RING_OUTER - RING_INNER}"/>
${SPRINKLES.map(([x, y]) => `  <circle cx="${x}" cy="${y}" r="${SPRINKLE_R}" fill="#111"/>`).join('\n')}
</svg>
`;

const png32 = png(32, render(32));
writeFileSync(join(OUT, 'favicon.svg'), svg, 'utf8');
writeFileSync(join(OUT, 'favicon.ico'), ico(32, png32));
writeFileSync(join(OUT, 'apple-touch-icon.png'), png(180, render(180)));
console.log('wrote site/favicon.svg, favicon.ico (' + (png32.length + 22) + ' bytes), apple-touch-icon.png');
